### ISSUE TITLE
OpenCensusTelemetryConverter.cs -> Null pointer can occure at line 337 on annotation.Description.value

### ISSUE THREAD

**Issue by yriedo** [Microsoft/ApplicationInsights-LocalForwarder#36]
Hi,
we try to use the localforwarder for our traces, with the following flow:

- Opentracing (Jaeger) -> OpenCensus Receiver (Jeager) -> Opencensus Exporter -> Azure Localforwarder -> App Insights

All works fine, I can see my traces in App Insights... but the dpendency call status is false? 

In addition the localforwarder logg this error:

-----------------------------------------

2019/07/22 08:40:34.534|ERROR|Could not track an incoming OpenCensus telemetry item. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.LocalForwarder.Library.OpenCensusTelemetryConverter.TrackTraceFromTimeEvent(TelemetryClient telemetryClient, TimeEvent evnt, Span span, Node peerInfo, String ikey)
   at Microsoft.LocalForwarder.Library.OpenCensusTelemetryConverter.TrackSpan(TelemetryClient telemetryClient, Span span, Node peerInfo, String ikey)
   at Microsoft.LocalForwarder.Library.Library.OnOcBatchReceived(ExportTraceServiceRequest batch, ServerCallContext callContext)
2019/07/22 08:40:34.534|ERROR|Could not track an incoming OpenCensus telemetry item. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.LocalForwarder.Library.OpenCensusTelemetryConverter.TrackTraceFromTimeEvent(TelemetryClient telemetryClient, TimeEvent evnt, Span span, Node peerInfo, String ikey)
   at Microsoft.LocalForwarder.Library.OpenCensusTelemetryConverter.TrackSpan(TelemetryClient telemetryClient, Span span, Node peerInfo, String ikey)
   at Microsoft.LocalForwarder.Library.Library.OnOcBatchReceived(ExportTraceServiceRequest batch, ServerCallContext callContext)
2019/07/22 08:40:34.534|ERROR|Could not track an incoming OpenCensus telemetry item. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.LocalForwarder.Library.OpenCensusTelemetryConverter.TrackTraceFromTimeEvent(TelemetryClient telemetryClient, TimeEvent evnt, Span span, Node peerInfo, String ikey)

----------------------------------------------

Can you help me, to understand whats going on?

Thank you
YR

**Comment by yriedo** [comment]
Hi,

I have tested locally the local forwarder and found the exception cause, it occurs on "OpenCensusTelemetryConverter.cs" at line 337. 

- telemetryClient.TrackTrace(span, evnt, peerInfo, annotation.Description.Value, ikey,
                    annotation.Attributes?.AttributeMap);

-> <annotation.Description.Value> can be null... this one generate the Exception
-- the traces comes from Opencensus Service Collector directly --

![Debug_View](https://user-images.githubusercontent.com/52417724/61638625-16dc7b00-ac9a-11e9-8654-fd361e708c56.png)

**Comment by lmolkova** [comment]
LocalForwarder is not supported and no future releases are planned. We are working with OpenTelemetry community and will be shipping per-language exporters. 

Which language do you use? 
If you are interested in python, there is a direct exporter to AppInsights https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python.

**Comment by yriedo** [comment]
Hi, thanks for the information. We work with Java.
I think, it will be good to indicate this information on your localforwarder webpage.

Until it comes for OpenTelemetry, I have done 2 code changes in the localforwarder (my local version). Now we are able to send data, whitout a specific code addition, from:
->OpenTracing (Java Jaeger) -> OpenCensus Collector -> Azure LocalForwarder -> App Insights

Regards
yRiedo
